### ISSUE TITLE
Build Problem (2.6.x)

### ISSUE THREAD

**Issue by willysr** [linuxmint/cinnamon-desktop#50] opened 2015-05-30 08:59 UTC
Hi

I'm building cinnamon-desktop 2.6.x and it failed with these messages
        prefix:                       /usr
        exec_prefix:                  ${prefix}
        libdir:                       /usr/lib
        bindir:                       ${exec_prefix}/bin
        sbindir:                      ${exec_prefix}/sbin
        sysconfdir:                   /etc
        localstatedir:                /var
        datadir:                      ${datarootdir}
        source code location:         .
        compiler:                     gcc
        cflags:                       -O2 -march=i486 -mtune=i686
        Maintainer mode:              no
        Use *_DISABLE_DEPRECATED:     no

Now type `make' to compile cinnamon-desktop
make  all-recursive
make[1]: Entering directory`/tmp/csb/cinnamon-desktop-2.6.3'
Making all in libcinnamon-desktop
make[2]: Entering directory `/tmp/csb/cinnamon-desktop-2.6.3/libcinnamon-desktop'
Makefile:765: libgsystem/.deps/libgsystem_la-gsystem-file-utils.Plo: No such file or directory
Makefile:766: libgsystem/.deps/libgsystem_la-gsystem-local-alloc.Plo: No such file or directory
make[2]: *** No rule to make target`libgsystem/.deps/libgsystem_la-gsystem-local-alloc.Plo'.  Stop.
make[2]: Leaving directory `/tmp/csb/cinnamon-desktop-2.6.3/libcinnamon-desktop'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/tmp/csb/cinnamon-desktop-2.6.3'
make: **\* [all] Error 2

the same script successfully build cinnamon 2.4.x

OS: 
Slackware-Current
GCC 4.9.2
GTK-2-2.24.27
GTK-3-3.14.12

**Comment by lots0logs** [comment] 2015-05-31 02:21
We're also running into this on Arch. I have found that copying the `.deps` directory to the location make expects it to be and running make again works. I've tried looking at the makefiles to find why the file path gets screwed up but I didn't see anything that would cause this. Anyway, here is the copy command I used so the build would complete on the second attempt:
```sh
cp -r 'cinnamon-desktop/src/cinnamon-desktop-2.6.4/libcinnamon-desktop/$(libgsystem_srcpath)/.deps' \
        'cinnamon-desktop/src/cinnamon-desktop-2.6.4/libcinnamon-desktop/libgsystem'
```

**Comment by willysr** [comment] 2015-05-31 02:31
i used this command to build it:
sed -i "s|include \$(libgsystem_srcpath)\/\$(DEPDIR)/libgsystem_la-gsystem-file-utils.Plo||" libcinnamon-desktop/Makefile
sed -i "s|include \$(libgsystem_srcpath)\/\$(DEPDIR)/libgsystem_la-gsystem-local-alloc.Plo||" libcinnamon-desktop/Makefile

ugly, but it works

**Comment by lots0logs** [comment] 2015-05-31 05:40
Thanks, it's ugly but it will stop our automated build from failing. That's good enough for now :smile:

**Comment by willysr** [comment] 2015-05-31 06:24
I wonder if other distro had this problem as well since i asked @clefebvre and he said it's working fine on Mint.

**Comment by lots0logs** [comment] 2015-05-31 07:23
I assume whatever is causing the problem is related to Arch using later versions of the automake tools than those used by Mint currently. :neutral_face:

**Comment by willysr** [comment] 2015-05-31 07:30
i'm using automake 1.14.1, same as Ubuntu 14.04 that is being used as base for LinuxMint 17.1

**Comment by lots0logs** [comment] 2015-05-31 07:32
Well so much for that theory! :sweat_smile:

**Comment by lots0logs** [comment] 2015-06-02 13:27
I think this may be a duplicate of linuxmint/cinnamon-desktop#48 which has a solution. I am trying it now...

**Comment by willysr** [comment] 2015-06-02 13:31
That's the solution i used as well :)
remove those 2 lines using sed

**Comment by willysr** [comment] 2015-06-02 13:33
ohh it's a different one i guess
anyway, both ways works

**Comment by lots0logs** [comment] 2015-06-02 13:36
Yeah, a little different. Not as ugly (only because its less code, hehe :wink:)
```sh
sed -i 's|subdir-objects||g' configure.ac
```

**Comment by leigh123linux** [comment] 2016-11-26 10:04
Is this still an issue or can it be closed now?

**Closed** 2016-11-26 10:05 UTC
