### ISSUE TITLE
Cinnamon fonts disappear after recovery from suspend

### ISSUE THREAD

**Issue by Psyfurius** [linuxmint/cinnamon-desktop#69] opened 2016-08-14 02:26 UTC
1) Linux Mint 18 'Sarah'. Cinnamon 64-bits. Kernel 4.4.0-34. Resolution 1366 x 768.
2) I put my laptop in Suspend mode. Then I turn it 'ON'.
3) The fonts from the task bar and menu disappear and the battery percent font turned black.
4) This happened one time.
![screenshot from 2016-08-13 21-42-44](https://cloud.githubusercontent.com/assets/21016013/17646740/d058c316-61a4-11e6-9794-83809d33e111.png)

**Comment by leigh123linux** [comment] 2016-11-26 10:51
Duplicate of

https://github.com/linuxmint/Cinnamon/issues/3442

**Closed by leigh123linux** 2016-11-26 10:51 UTC
