### ISSUE TITLE
Linux Mint 17 Ctrl+Alt+up arrow (switch to workspace selector) causes corruption of characters

### ISSUE THREAD

**Issue by geoffsh** [linuxmint/cinnamon-desktop#15] opened 2014-06-27 00:27 UTC
Linux Mint 17 'Qiana' - Cinnamon 64 bit 
Cinnamon version 2.2.13
Intel Core 15 650 @ 3.2 GHz x 2
Memory 8 GB
120GB Samsung SSD
NVIDIA G73 (GeForce 7600 GS)
NVidia video driver version 304.117 and 304.121

When pressing Ctrl+Alt+up arrow to display the workspace switcher panel, characters rendered by Cinnamon are replaced with partial rendering only - that is black squares where the characters would be, or in some cases letter shaped shadows, and the vanilla mint menu icon is displayed. Attached screenshot shows that time desklet is also affected. Applications are not affected, so it does not appear to be a general driver rendering issue. 

Using the Ctrl+Alt+L & R arrow keys to switch workspaces or the workspace switcher taskbar applet does not affect rendering at all, so the issue appears to be related to the rendering of the workspace switching panel itself. Possibly switches to a specific rendering mode and does not switch back?

This happened when using the recommended driver (304.117) and the newer driver from NVidia (304.121), so I think it may be a general driver interaction issue. I don't know whether it happens in the Nouveau driver - I never use that.

Problem is reproducible approximately 70% of the time.
![worskpace switcher issue](https://cloud.githubusercontent.com/assets/8000883/3406521/0ae77b5a-fd91-11e3-8e1f-fcddd66204e1.png)

**Comment by leigh123linux** [comment] 2016-11-26 11:02
Duplicate of

linuxmint/Cinnamon#3442

**Closed by leigh123linux** 2016-11-26 11:02 UTC
